// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmcbxrssyqkiimazipvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtY2J4cnNzeXFraWltYXppcHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NDAxNDAsImV4cCI6MjA2MDExNjE0MH0.lwoCjkLr6Nrf0WPIDQQhVSPcSU_HV5f-NFDxeUFfivI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);